spring:
  application:
    name: userService

  zipkin:
    base-url: http://localhost:9411

  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: update

  # cloud:
  #   gcp:
  #     project-id: reels-orbit
  #     sql:
  #       instance-connection-name: reels-orbit:asia-south2:reels-orbit-sql
  #       database-name: users
  #   generate-ddl: true
  #   datasource:
  #     username: postgres
  #     password: password

  # credentials:
  #   location: file:./userService/reels-orbit-3f2299e99b9d.json

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081

feing-payment-service: PaymentService
feing-payment-service-url: http://localhost:8053/payments/create
