spring:
  config:
    import:
      - optional:configserver:http://localhost:8083
  application:
    name: securityService
  profiles:
    active: dev

# Oauth2 Google
#spring.security.oauth2.client.registration.google.client-id=${google-client-id}
#spring.security.oauth2.client.registration.google.client-secret=${google-client-secret}

# Oauth2 Facebook
#spring.security.oauth2.client.registration.facebook.client-id=${facebook.client-id}
#spring.security.oauth2.client.registration.facebook.client-secret=${facebook.client-secret}
#spring.security.oauth2.client.registration.facebook.scope=email,public_profile

# Oauth2 Twitter
#spring.security.oauth2.client.registration.twitter.client-id=${twitter.client-id}
#spring.security.oauth2.client.registration.twitter.client-secret=Z9K7TF-PQn1CAtGY4BDywFrrdiCg7PTyzBBP7N6PcdTiFgYNlJ
#spring.security.oauth2.client.registration.twitter.scope=${twitter.scope}
#spring.security.oauth2.client.registration.twitter.authorization-grant-type=${twitter.authorization-grant-type}
#spring.security.oauth2.client.registration.twitter.redirect-uri=${twitter.redirect-uri}
#spring.security.oauth2.client.provider.twitter.authorization-uri=${twitter.authorization-uri}
#spring.security.oauth2.client.provider.twitter.token-uri=${twitter.token-uri}
#spring.security.oauth2.client.provider.twitter.user-info-uri=${twitter.user-info-uri}

#eureka
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#zipkin
#spring.zipkin.base-url=http://ReelsOrbit-zipkin:9411

#OpenFeing
#feing-user-service-name=${feing-user-service-name}
#feing-user-service-url=${feing-user-service-url}